
name: tox workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs: 
 unittests:
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version : [3.8]
        # [3.8, 3.9, 3.11]
        include:
          - python-version: 3.8
            toxenv: "py38-cover,report" #,codecov"
          - python-version: 3.9
            toxenv: "py39-cover,report" #,codecov"
          - python-version: 3.11
            toxenv: "py311-cover,report" #,codecov"
        exclude:
          # IDEA py39 on windows has errors so we exclude it for now
          - os: windows-latest
            python-version: 3.9

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        python -m pip install --upgrade setuptools tox 
        pip --version
        virtualenv --version
        tox --version
    - name: Test with tox
      run: |
        tox -v
      env:
        TOXENV: ${{ matrix.toxenv }}
        # MPLBACKEND: "Agg"
